### ISSUE TITLE
guidance on contributing

### ISSUE THREAD

**Issue by gajowi** [Unidata/thredds-docker#105]
Hi @julienchastang I'm gearing up to contribute some requests and would appreciate some guidance on how to make things work for you.  I made a fork and managed to integrate travis-ci and start my own feature/bugfix branch which tests OK. Should I make pull requests to Unidata/thredds-docker master or somewhere else?  I suspect you want to test elsewhere in any case - you might want a PR to a clean branch off master :-P Perhaps you should add a develop branch and keep master for code releases.

In any case my first code fix is at: https://github.com/gajowi/thredds-docker/tree/gajowi-systemPrefs-patch and I have an internal PR to merge it into my copy/fork of master... That is probably not helpful, but I'm learning how github and git works more deeply along the way. You can probably see that PR at: https://github.com/gajowi/thredds-docker/pulls

As you may guess, I'm really not sure of the 'right way' of approaching this - but you did say you would like PRs. :-)

The next two items on my list are making gosu work again (you broke it with the security manager change), and improving the travis test.  At this point I thought I'd generate fixes rather than complaints - though I tend to think it is better to complain first so you can make fixes that suit you (and your broader context) rather than having to reverse engineer my fixes. It is a fine line, but I suspect most of my fixes will be trivial so best provided in PRs if we can get the process right.

regards,

Gareth

**Comment by gajowi** [comment]
ps. Perhaps it would be good if I could add my own  feature branches - but I see you are doing your own development in a fork in any case - and merging to Unidata master.  I suppose I should follow that lead.

**Comment by gajowi** [comment]
BTW.  Repeating this process for some other features, I recall why I made a PR to master in my own fork. Github is enabling me to be lazy (hooray) by letting me edit in the browser and suggesting I commit to a new branch with a PR.  This seemed a good idea in this case, especially if travic-ci is working so the change gets tested in a way that others on the project understand.  I now have 2 extra PRs for different aspects of testing with travis - one was just committed now and failed testing. I'll edit further to attempt to make the existing PR better.

**Comment by julienchastang** [comment]
The work flow I would suggest is:

- Create a fork
- Create issues on the main (`origin`) repo, if that has not been done already
- Create local feature branches off your fork
- Push your feature branch to your fork on github
- Submit a pull request. In the comments section reference your issue above (e.g., closes #soandso)
- The PR will trigger a travis test (you don't necessarily have to set up travis for your fork, but you can. Sometimes this is useful for experimenting with travis)

Again, sorry I broke the entrypoint. Live and learn.

**Comment by gajowi** [comment]
Thanks.  It is nice to be able to test before you make a PR so I'll keep my travis setup and add steps to have my own PR (at least for simple cases where I can do all the work in the browser and github).  I found I have to cancel my own internal PR before I can make a PR to Unidata's master. I've just made one PR and will make another two (and then maybe comment to add cross references to issues).

**Comment by julienchastang** [comment]
Closing this unless there are objections. Can always reopen later.
