### ISSUE TITLE
Improve Parameterization of javaopts.sh script with Compose Environment Variables Files

### ISSUE THREAD

**Issue by julienchastang** [Unidata/thredds-docker#137]
We can take advantage of this: https://docs.docker.com/compose/environment-variables/

**Comment by isuftin** [comment]
https://github.com/Unidata/thredds-docker/pull/141

I've gone ahead and updated all the parameterization. This PR goes beyond just javaopts.sh. It's easier to do everything in one PR instead of having multiple feature branches attacking the same environments file
