### ISSUE TITLE
Put the TDM in its Own Docker Project Repo

### ISSUE THREAD

**Issue by julienchastang** [Unidata/thredds-docker#138]
Consider putting the TDM in its own Docker Project Repo. This would simplify things especially on the [thredds-docker dockerhub page](https://hub.docker.com/r/unidata/thredds-docker/) at the expense of a new repository.

**Comment by julienchastang** [comment]
@isuftin @kwilcox @rsignell-usgs @lesserwhirls @cwardgar FYI, the TDM is going into its own project: https://github.com/Unidata/tdm-docker

**Comment by julienchastang** [comment]
Note to self to also deal with the snapshot branches with respect to this issue.

**Comment by isuftin** [comment]
Once we have most PRs pulled into here for updated Dockerfiles and Compose file, we can remove the TDM Dockerfile from here
