### ISSUE TITLE
Is the thredds-quickstart service necessary?

### ISSUE THREAD

**Issue by isuftin** [Unidata/thredds-docker#155]
@julienchastang The only difference I see if the path mapping.

**Comment by julienchastang** [comment]
I think this was originally put in by @kwilcox. I actually like to have it around for testing and experimentation purposes. I was just using it yesterday.

**Comment by isuftin** [comment]
@julienchastang What's your use case for it as opposed to using thredds-production?

**Comment by julienchastang** [comment]
For example, yesterday, I fired it up with the environment variables file section (e.g., `env_file`) to make sure I understood the mechanism. I then entered the container and I could see the environment variables. This had no production value. Like I say, it is simply for testing and experimentation.

**Comment by isuftin** [comment]
@julienchastang Ok that works.
