### ISSUE TITLE
Dockerfile build fails

### ISSUE THREAD

**Issue by tlechauve** [Unidata/thredds-docker#162]
HDF Group change their directory structure

from:
https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8.17/ (used in 4.6.6)

to:
https://support.hdfgroup.org/ftp/HDF5/releases/hdf5-1.8/hdf5-1.8.17/

This change raises an error while building thredds-docker image

Fix (line 54)
Replace: 
https://support.hdfgroup.org/ftp/HDF5/releases/${HDF5_VER}/src/${HDF5_FILE}

By:
https://support.hdfgroup.org/ftp/HDF5/releases/${HDF5_VER%.*}/${HDF5_VER}/src/${HDF5_FILE}

I don't know how to make a pull request, sorry :x

**Comment by julienchastang** [comment]
Merci Thomas. I will look into this as soon as I can.
