### ISSUE TITLE
slow tomcat start and entropy

### ISSUE THREAD

**Issue by gajowi** [Unidata/thredds-docker#172]
I noticed very slow service startup (particularly well after boot of the underlying VM).
This turns out to be a well discussed problem with tomcat - see: https://gandharvkapoor.wordpress.com/2017/02/23/spring-boot-slow-boot-up-random-vs-urandom/
http://www.labouisse.com/misc/2014/06/19/tomcat-startup-time-surprises

I think a good solution for thredds-docker is to add to javaopts.sh
Adding the following option has worked for me:
URAND="-Djava.security.egd=file:/dev/urandom"
(and then append that to JAVA_OPTS

Can you also feed this upstream to the TDS developers please.  It could be documented along with performance tuning.

BTW I've also added:
JGC="-XX:ParallelGCThreads=2"
to try and avoid a proliferation of GC threads but it hasn't made an obvious difference (probably I just have not looked hard enough).

regards,

Gareth

**Comment by julienchastang** [comment]
Thanks @gajowi. I would gladly accept a PR in this area. Also pinging the THREDDS guys about your finding (@cwardgar @lesserwhirls).
