### ISSUE TITLE
Update the three-month old THREDDS 5.0-snapshot container

### ISSUE THREAD

**Issue by rsignell-usgs** [Unidata/thredds-docker#173]
@julienchastang, please update the 5.0-snapshot container on Docker hub with the latest functioning version.

The one that is there is 3 months old, and a lot has happened since then:
https://github.com/Unidata/thredds/network

**Comment by julienchastang** [comment]
closed by #175. Dockerhub autobuild has completed. @rsignell-usgs are we good?
