### ISSUE TITLE
Migrate to unidata/tomcat-docker:8.5

### ISSUE THREAD

**Issue by julienchastang** [Unidata/thredds-docker#191]

**Comment by julienchastang** [comment]
@kwilcox or anyone out there listening. Is there a problem with this ending up in `master` or `latest`?

**Comment by kwilcox** [comment]
Sounds good. https://github.com/Reading-eScience-Centre/ncwms moved to it yesterday and I can move https://github.com/axiom-data-science/docker-erddap to it right now.

**Comment by julienchastang** [comment]
closed by #197
