### ISSUE TITLE
Can't authenticate restrictedDatasetUser

### ISSUE THREAD

**Issue by duanbeckett** [Unidata/thredds-docker#210]
I haven't been able to get working the restricting access to THREDDs datasets feature. I have it working on a non-dockerized instance of THREDDs on my local machine and have exhausted almost every avenue I can think of to get it working, but with no luck. The end result is the browser prompts for a username and password, but ends up with this response:

![screen shot 2018-11-20 at 4 25 53 pm](https://user-images.githubusercontent.com/45191233/48754882-6b80be00-ece7-11e8-8838-b6705a2b3909.png)

I'm using digested passwords, I believe I have set up the tomcat roles and users correctly, but there is some issue when TOMCAT attempts to authenticate the request.

Just wanted to check if this feature works with the current release and if so are there any extra steps other than those listed on the unidata site that are required?

**Comment by julienchastang** [comment]
Sorry for the delayed response.(I've been on Thanksgiving break.) I have gotten Tomcat users/roles/digested passwords to work correctly (for example, with the TDM) but it is rather fragile.  I'll take a closer look this week.

**Comment by duanbeckett** [comment]
Awesome. Thank you for looking into this. My gut feeling is it's something to do with Docker, but 
I am at the ragged edge of my current understanding of Docker and TOMCAT! Let me know if you would like to see any of my setup files.

**Comment by julienchastang** [comment]
One thing that I notice from your screenshot above is port `82` in the URL. Are you mapping TCP port `82` on the docker host to somewhere in the container? I also wonder if you need to do anything with port `443`/`8443`. See below.

Apart from that, there is some related [documentation here](https://github.com/Unidata/tdm-docker#tdm-password-and-coordination-with-the-tds) and [also here](https://github.com/Unidata/tomcat-docker#digested-passwords). Specifically, I wonder if you are digesting the password correctly.

If using this container, I would digest the password like this:

`docker run tomcat  /usr/local/tomcat/bin/digest.sh -a "SHA" mysupersecretpassword`

**Comment by duanbeckett** [comment]
I've mapped TCP 82 port to 8080 on the container. Here is a snippet from my docker-compose.yml file:

 ```
  ports:
      - "82:8080"
      - "444:8443"
      - "8444:8443"
```


Also here is my tomcat-user.xml file:


```
<?xml version="1.0" encoding="utf-8"?>
<tomcat-users xmlns="http://tomcat.apache.org/xml"
              xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
              xsi:schemaLocation="http://tomcat.apache.org/xml tomcat-users.xsd"
              version="1.0">

  <role rolename="tdsConfig" description="can change THREDDS configuration files"/>
  <role rolename="admin"/>
  <role rolename="manager"/>
  <role rolename="restrictedDatasetUser"/>

<role rolename="oceanmaps_fc_ens"/>
<user username="usera" password="b6d79a7ef977b95144e42f258c07a36bb880eab634607934098050e7a8cb4001$1$2c87162944249be8bbb368032dd7ca952355e071" roles="oceanmaps_fc_ens,restrictedDatasetUser"/>
<user username="userb" password="test" roles="oceanmaps_fc_ens,restrictedDatasetUser"/>
<user username="admin" password="b6d79a7ef977b95144e42f258c07a36bb880eab634607934098050e7a8cb4001$1$2c87162944249be8bbb368032dd7ca952355e071" roles="admin,manager,tdsConfig"/>
<user username="duan" password="b6d79a7ef977b95144e42f258c07a36bb880eab634607934098050e7a8cb4001$1$2c87162944249be8bbb368032dd7ca952355e071" roles="oceanmaps_fc_ens,admin,manager,tdsConfig,restrictedDatasetUser"/>
</tomcat-users>

```

I used the following to create the digested password:

`docker run tomcat /usr/local/tomcat/bin/digest.sh -a "SHA" test`

I've been testing authentication with wget as it is difficult to get consistent behaviour using a browser.

I'm pretty confident the digested password is correct as when I go to admin/debug it authenticates correctly:

```
rigel:tmp dbeckett$ wget --user=admin --password=test --no-check-certificate https://127.0.0.1:8444/thredds/admin/debug
--2018-11-28 13:05:02--  https://127.0.0.1:8444/thredds/admin/debug
Connecting to 127.0.0.1:8444... connected.
WARNING: cannot verify 127.0.0.1's certificate, issued by ‘CN=127.0.0.1,OU=BoM,O=OrgName,L=Melbourne,ST=Victoria,C=AU’:
  Self-signed certificate encountered.
HTTP request sent, awaiting response... 401 
Authentication selected: Basic realm="THREDDS Data Server"
Reusing existing connection to 127.0.0.1:8444.
HTTP request sent, awaiting response... 200 
Length: unspecified [text/html]
Saving to: ‘debug’
```

But when I try to access a restricted dataset I get the following response:

```
rigel:tmp dbeckett$ wget --user=usera --password=test http://127.0.0.1:82/thredds/dodsC/oceanmaps_fc_ens/ocean_fc_ensemble_2018111512_048_eta.nc.html
--2018-11-28 13:06:38--  http://127.0.0.1:82/thredds/dodsC/oceanmaps_fc_ens/ocean_fc_ensemble_2018111512_048_eta.nc.html
Connecting to 127.0.0.1:82... connected.
HTTP request sent, awaiting response... 307 
Location: http://127.0.0.1:82/thredds/restrictedAccess/oceanmaps_fc_ens [following]
--2018-11-28 13:06:38--  http://127.0.0.1:82/thredds/restrictedAccess/oceanmaps_fc_ens
Reusing existing connection to 127.0.0.1:82.
HTTP request sent, awaiting response... 401 
Authentication selected: Basic realm="THREDDS Data Server"
Reusing existing connection to 127.0.0.1:82.
HTTP request sent, awaiting response... 401 

Username/Password Authentication Failed.
```

I have, essentially, the same setup of TOMCAT and THREDDs on my desktop (non-dockerized) and it all seems to work.

**Comment by julienchastang** [comment]
My working hypothesis is we are somehow messing up the port mappings since you say it works just fine on the host without the container. Drop all port mappings and use `network_mode: "host"`. With this option, we'll be using the docker host network instead. Note that the TDS will now run on `8080`. This may not be ideal for what you are trying to achieve but I just want to get something working first.

Also tell me more about your Docker host. On what OS are you running Docker?

**Comment by duanbeckett** [comment]
I'll give that a go when back at work (currently at home till Monday). I agree, getting something working first is the way to go! My computer at work is a Mac running (I think) High Sierra. I'll need to double check what version of Docker I'm using. If it's not the latest version it is close to. Thanks again for looking into this. I apologise in advance if this problem is due to something stupid that I'm doing.

**Comment by julienchastang** [comment]
Ahh OK that is an important clue. You have to remember that when you are running Docker on a Mac there is an extra level of indirection, namely the virtual machine intermediate. Docker does not run natively on macOS, so the `network_mode: "host"` idea is not going to work. That may be the problem here.

https://docs.docker.com/docker-for-mac/networking/
