### ISSUE TITLE
upgrading to Tomcat version 9

### ISSUE THREAD

**Issue by zdefne-usgs** [Unidata/thredds-docker#309]
What does it take to upgrade to Tomcat version 9?

**Comment by zdefne-usgs** [comment]
The point is symlinks (implemented with ln -s in unix for combining files from different folders in a single folder without copying them) do not display on the browser with Thredds server. According to some googling editing context.xml on a Tomcat v9 is supposed to resolve the issue. But the latest version of Threddds-docker I had installed (unidata/thredds-docker:5.4) comes with a Tomcat version 8.x.

**Comment by julienchastang** [comment]
Have you tried `unidata/thredds-docker:5.5` ?

**Comment by ana-v-espinoza** [comment]
Zafer,

The latest version of thredds-docker is 5.5, which does use tomcat9.

See the thredds-docker:5.5 [Dockerfile](https://github.com/Unidata/thredds-docker/blob/f957e27b5a41e710ae181544b2656746281e9a70/Dockerfile#L1)
thredds-docker on [dockerhub](https://hub.docker.com/r/unidata/thredds-docker/tags)

Also available is the 5.6-SNAPSHOT, which will have the most recent development updates from the THREDDS team.

Let me know if this helps so we can close this issue.

Thank you,

-- ana

**Comment by zdefne-usgs** [comment]
Thank you @ana-v-espinoza . I have just realized that. I was looking at the tagged versions on [this repo only](https://github.com/Unidata/thredds-docker/tags). It all makes sense now. I have upgraded to v5.5 and my issue has been resolved.  Thanks!
