### ISSUE TITLE
Missing tds-plugin-jar-with-dependencies.jar in 5.5 docker image

### ISSUE THREAD

**Issue by tlvu** [Unidata/thredds-docker#310]
To report a non-security related issue, please provide:

* the version of the software with which you are encountering an issue: `unidata/thredds-docker:5.5` (https://hub.docker.com/r/unidata/thredds-docker/tags)
* environmental information (i.e. Operating System, compiler info, java version, python version, etc.): versions in the docker image
* a description of the issue with the steps needed to reproduce it

I see the jar is being added to the docker image here https://github.com/Unidata/thredds-docker/blob/c75cba0a4cb503cd94fae7fc8bd0b6cafb673f46/Dockerfile#L62-L63

But why is it not in the published docker image itself?

```
$ docker run --rm unidata/thredds-docker:5.5 ls -a /usr/local/tomcat/webapps/thredds/WEB-INF/lib/tds-plugin-jar-with-dependencies.jar
ls: cannot access '/usr/local/tomcat/webapps/thredds/WEB-INF/lib/tds-plugin-jar-with-dependencies.jar': No such file or directory

$ docker run --rm -it unidata/thredds-docker:5.5 bash
root@b78ff9edbede:/usr/local/tomcat# cd /
root@b78ff9edbede:/# find . -name tds-plugin-jar-with-dependencies.jar
root@b78ff9edbede:/# find . -name '**.jar' |grep tds
./usr/local/tomcat/webapps/thredds/WEB-INF/lib/tds-ugrid-5.5.jar
root@b78ff9edbede:/#
```

According to the documentation here https://docs.unidata.ucar.edu/tds/5.5/userguide/adding_ogc_iso_services.html#nciso-configuration that jar is needed for ncISO Configuration

![Image](https://github.com/user-attachments/assets/3180534d-f149-4319-b3d7-726f8ea266b0)

**Comment by tlvu** [comment]
Work-around for those in need: here is a working Thredds docker image `pavics/thredds-docker:5.5-unidata-2024-11-19-with-tds-plugin-jar-with-dependencies.jar` with the missing `tds-plugin-jar-with-dependencies.jar`.

```
$ docker run --rm pavics/thredds-docker:5.5-unidata-2024-11-19-with-tds-plugin-jar-with-dependencies.jar ls -a /usr/local/tomcat/webapps/thredds/WEB-INF/lib/tds-plugin-jar-with-dependencies.jar
/usr/local/tomcat/webapps/thredds/WEB-INF/lib/tds-plugin-jar-with-dependencies.jar
```

The `Dockerfile` used to create it:
```
$ cat Dockerfile 
FROM unidata/thredds-docker:5.5

ENV THREDDS_ISO_JAR_URL https://downloads.unidata.ucar.edu/tds/5.5/tds-plugin-2.4.6-jar-with-dependencies.jar

RUN curl -fsL "${THREDDS_ISO_JAR_URL}" -o ${CATALINA_HOME}/webapps/thredds/WEB-INF/lib/tds-plugin-jar-with-dependencies.jar
```

Link to a related issue found: https://github.com/Unidata/tds/issues/519

**Comment by julienchastang** [comment]
~~The `curl` command failed silently. The jar in question may have been momentarily unavailable. Rebuilding now.~~

Edit: `5.5` does not have the jar in question. `latest` (only on git) and `5.6-SNAPSHOT` ([available at DockerHub](https://hub.docker.com/r/unidata/thredds-docker/tags)) do.

**Comment by tlvu** [comment]
> The `curl` command failed silently. The jar in question may have been momentarily unavailable. Rebuilding now.

Oh thanks for the very fast feedback !  How about adding a check like `ls -l ${CATALINA_HOME}/webapps/thredds/WEB-INF/lib/tds-plugin-jar-with-dependencies.jar` after the `curl` to check the jar is really there?

**Comment by tlvu** [comment]
@julienchastang FYI, I pulled the latest published build of `unidata/thredds-docker:5.5` 10 mins ago and the jar is still missing.

```
$ docker run --rm unidata/thredds-docker:5.5 ls -a /usr/local/tomcat/webapps/thredds/WEB-INF/lib/tds-plugin-jar-with-dependencies.jar
ls: cannot access '/usr/local/tomcat/webapps/thredds/WEB-INF/lib/tds-plugin-jar-with-dependencies.jar': No such file or directory
```

**Comment by julienchastang** [comment]
Right. I know. I am looking into it.

**Comment by julienchastang** [comment]
@tlvu, if possible, please use `unidata/thredds-docker:5.6-SNAPSHOT`. Thanks.

**Comment by tlvu** [comment]
> [@tlvu](https://github.com/tlvu), if possible, please use `unidata/thredds-docker:5.6-SNAPSHOT`. Thanks.

Isn't snapshot means it's not released yet?  I'd rather stick to a released version.  My work-around `pavics/thredds-docker:5.5-unidata-2024-11-19-with-tds-plugin-jar-with-dependencies.jar` works.

But glad to know the problem is already fixed for 5.6 and up.

Since I have your attention, is it possible to not re-release on an existing docker tag?  It's very confusing because two persons can both have the image `unidata/thredds-docker:5.5` but in fact they do not have the same image because, example, one person pulled a weeks ago and the other person pulled today with the rebuild.

On each rebuild, you can add a date to your tag to clarify, example `5.5-241119`.

**Comment by julienchastang** [comment]
> Isn't snapshot means it's not released yet? I'd rather stick to a released version.

It is very close to `5.5`. See git branches for details.

> Since I have your attention, is it possible to not re-release on an existing docker tag?

This is unavoidable and standard practice in Docker world. See canonical, parent Apache Tomcat containers that have the same issue as you describe. If you want to distinguish between docker image versions, examine the build hash. That is what we do when we need to determine if there is a new Apache Tomcat image even though the tag is exactly the same. On this topic, these images are regularly rebuilt based on upstream changes as required by company security policies.

**Comment by tlvu** [comment]
> On this topic, these images are regularly rebuilt based on upstream changes as required by company security policies.

Right, totally agreed.  So how about you let `5.5` "evolve" but for the same build you also add a tag `5.5-builddate`.

Basically for each new build you will have 2 tags on the exact same build hash: `5.5-builddate` and `5.5`.  The `5.5-builddate` is unique and never re-used (never evolve).  The `5.5` will evolve.

Someone wanting to use your image as base image will use the evolving tag `5.5`.

Someone deploying into production that wants strict reproducibility will use the `5.5-241120` flavor.  `5.5-241120` is much more user friendly than a hash.

I found an article that explain more or less the same idea but in more details https://stevelasker.blog/2018/03/01/docker-tagging-best-practices-for-tagging-and-versioning-docker-images/

**Comment by julienchastang** [comment]
I don't think the [parent Apache Tomcat containers](https://hub.docker.com/_/tomcat/tags), which this project is modeled after, implement anything like your suggestion. The unique identifier you mentioned already exists in the form of a digest hash. Furthermore, due to shoestring budgets and ever-dwindling resources, I don't foresee having the free cycles to pursue this idea. I am closing this issue.
