### ISSUE TITLE
Using "docker" in a git repository name

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds-docker#47]
Food for thought (actually, more than that), as this is not looked upon in a friendly way by Docker due to trademarks...

https://www.andreas-jung.com/contents/dont-use-docker-in-github-repo-names-or-as-twitter-handle

**Comment by julienchastang** [comment]
According to this link from Jung's blog, the Docker representative, Chris Palmero, states:

> The company's position is that using the registered trademark Docker as the **_first part_** of a repo name suggests an association with, or a sponsorship by, Docker. "

(Bold, italics are mine.)

This repo does not start with "docker", therefore this statement does not apply to us. Can we close this issue?

**Comment by lesserwhirls** [comment]
Sounds good - I missed that part. Thanks Julien!
