### ISSUE TITLE
ncsos.jar

### ISSUE THREAD

**Issue by julienchastang** [Unidata/thredds-docker#69]
@kwilcox @lesserwhirls @cwardgar is it possible to `curl` the `ncsos.jar` (versioned, ideally) from an artifact server somewhere (even at Unidata) rather than committing this `jar` to version control?

**Comment by cwardgar** [comment]
Not sure, but I can say at least that it's not available in any Unidata Maven repo.

**Comment by isuftin** [comment]
Can be obtained from https://github.com/asascience-open/ncSOS/releases

Example: `curl -o ncsos.jar https://github.com/asascience-open/ncSOS/releases/download/v1.4.3/ncsos-1.4.3.jar -L`

**Comment by isuftin** [comment]
Also available @ http://maven.asascience.com/maven/ncsos-releases/com/asascience/ncsos/

**Comment by lesserwhirls** [comment]
@julienchastang - we will be bundling the ncSOS plugin with the next 4.6 release, as well as 5.0, so this won't be an issue soon.
