### ISSUE TITLE
travis builds latest but tests 4.6.6

### ISSUE THREAD

**Issue by gajowi** [Unidata/thredds-docker#75]
I'm prepared to be wrong but...

I had a look at your automated testing and you explicitly build and tag 'latest' but then test `thredds-quickstart` with `docker-compose`, which has:
thredds-quickstart:
  image: `unidata/thredds-docker:4.6.6`

So I think you are not testing what was built.

regards.

**Comment by julienchastang** [comment]
This observation does not surprise me. In fact, #39 indicates we have some work to do in this area. I would gladly take a PR if you ideas for improving the travis build. (For the next couple of weeks, I am submitting a grant application so this project will be temporarily lower priority, but I still aim on pushing it forward. This project is more fun than grant writing.)

**Comment by gajowi** [comment]
Hi @julienchastang, I think this needs a little extra work. The check now compares a page returned with a reference page. The reference page will go out of date and contains build and version info. 
I suspect that testing that the curl invocation completes successfully is sufficient. There is no great need to check the content - but if you do, a simpler check that the page contains something expect should be sufficient. - say: grep -q 'Test Single Dataset'. or 'THREDDS Data Server'

**Comment by julienchastang** [comment]
@gajowi Yeah, I know what you mean. I thought about that too. The current test may be too sensitive on account of the embedded version information, and we'll essentially get false positives. This will become even more of an issue if we start testing snapshot branches. But apart from that, it actually took me a while to get this test working. The fact that you have to "ping" the TDS and wait for a while before you can issue the `curl` command to compare expected with actual took me a while to figure out. I want to let this rest for a bit before I get back to it. Feel free to open a new issue or a PR. Thanks again.
