### ISSUE TITLE
licensing

### ISSUE THREAD

**Issue by gajowi** [Unidata/thredds-docker#86]
I'm working on releasing a hyrax docker project and just realised I've copied significantly from this project. (especially as I'm using the same underlying tomcat container) Before I release I'd like to be clear on licensing.  I'm currently planning on applying a cc-by license, treating the content as predominantly configuration data and instructions, rather than being original software, but I could change to an MIT license. In any case it would help for it to be clear how this project is licensed. I think attributing it is clear, with a link to the github site and an indicative date.

I'm hoping/expecting you are happy to provide a permissive license. Github has advice at: https://github.com/blog/1530-choosing-an-open-source-license

**Comment by julienchastang** [comment]
I'll let @lesserwhirls @cwardgar chime in here since I see this project as just an extension of the TDS project.

**Comment by lesserwhirls** [comment]
Bringing in @ethanrd. Currently, the TDS uses a "custom" license from the netCDF-C library. However, we've been discussing using a straight-up BSD 3-Clause license. That will take some time to move forward, but since this is not derivative code, I'd recommend using the BSD 3-clause license here.

**Comment by ethanrd** [comment]
I agree. Seems fine to use the BSD 3-clause license for the thredds-docker project.
