### ISSUE TITLE
Add contributors file and CLA

### ISSUE THREAD

**Issue by lesserwhirls** [Unidata/thredds-docker#95]
@dopplershift - think we're good on the CLA/infrastructure and workflow to add it to this project?

**Comment by dopplershift** [comment]
I think so. I haven't seen any problems so far.

**Comment by julienchastang** [comment]
@dopplershift, @lesserwhirls Any update on this? Thanks.

**Comment by dopplershift** [comment]
@lesserwhirls what was the rationale behind doing a CLA on this particular repo? The main thredds one I would understand.

**Comment by julienchastang** [comment]
In fact, that's what I am doing for other aspects of this project, as well. For example, citation; simply cite the main THREDDS DOI. I could have a pointer the README to the TDS CLA.

**Comment by dopplershift** [comment]
Well the question becomes whether it's worth setting up Clahub/CLA Assistant to check CLAs for pull requests.

**Comment by lesserwhirls** [comment]
I cannot recall the rationale. I'd say we are ok to not do a CLA on this.

**Comment by julienchastang** [comment]
OK, I'll close it for now. Can always reopen later.
